---
title: "P8105_hw3_wl2829"
author: "Wentong"
date: "10/15/2021"
output: github_document
---

```{r setup}
library(tidyverse)
library(dplyr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Problem 1

```{r}
library(p8105.datasets)
data("instacart")
```

```{r}
instacart %>% 
  count(aisle_id) %>% 
  nrow()   ## The total number of aisles.

instacart %>% 
  distinct() %>% 
  count(aisle, name = "aisle_n") %>% 
  mutate(aisle_n = as.numeric(aisle_n)) %>% 
  arrange(desc(aisle_n)) %>%
  filter(aisle_n == max(aisle_n))
## "Fresh vegetables" has the most items. The number of orders is 150609.
```

```{r}
plot_df = 
  instacart %>% 
  distinct() %>% 
  count(aisle, name = "aisle_n") %>% 
  mutate(aisle_n = as.numeric(aisle_n)) %>% 
  filter(aisle_n >= 10000) %>% 
  arrange(desc(aisle_n)) %>% 
  mutate(
    aisle = factor(aisle),
    aisle = forcats::fct_reorder(aisle, sort(aisle_n))) %>% 
  ggplot(aes(x = aisle, y = aisle_n)) +
  geom_point() + 
  coord_flip() +
  labs(
    title = "Number of items more than 10000",
    x = "number of itmes",
    y = "name of items",
    caption = "Data from instacart; number of items."
  )
```

```{r}
Bi_df = 
  instacart %>% 
  filter(aisle == "baking ingredients") %>%   ## select the specific aisle
  count(product_name, name = "product_n") %>% ## count the number of each product
  arrange(desc(product_n)) %>% 
  head(3) %>% ## order the number and pick the three most popular items
  mutate(aisles_name = "baking ingredients") %>% 
  select(aisles_name, product_name, product_n) ## rearrange the table

dfc_df = 
  instacart %>% 
  filter(aisle == "dog food care") %>% 
  count(product_name, name = "product_n") %>% 
  arrange(desc(product_n)) %>% 
  head(3) %>% 
  mutate(aisles_name = "dog food care") %>% 
  select(aisles_name, product_name, product_n)

pvf_df = 
  instacart %>% 
  filter(aisle == "packaged vegetables fruits") %>% 
  count(product_name, name = "product_n") %>% 
  arrange(desc(product_n)) %>% 
  head(3) %>% 
  mutate(aisles_name = "packaged vegetables fruits") %>% 
  select(aisles_name, product_name, product_n)

three_aisles_df = 
  rbind(Bi_df, dfc_df, pvf_df)
```
Make a table showing the mean hour of the day at which Pink Lady Apples and Coffee Ice Cream are ordered on each day of the week; format this table for human readers (i.e. produce a 2 x 7 table).

```{r}
mean_hour_df = 
  instacart %>% 
  filter(product_name %in% c("Coffee Ice Cream", "Pink Lady Apples")) %>% 
  group_by(product_name, order_dow) %>% 
  summarize(
    mean_hour = mean(order_hour_of_day)
  ) %>% 
  pivot_wider(
    names_from = order_dow,
    values_from = mean_hour
  ) %>% 
  rename("Sun" = "0","Mon" = "1", "Tue" = "2", "Wed" = "3", "Thu" = "4", "Fri" = "5", "Sat" = "6")
```


## Problem 2
```{r}
library(p8105.datasets)
```

```{r}
BRFSS_df = 
  brfss_smart2010 %>% 
  ## need change the variables' name
  janitor::clean_names() %>% 
  rename(state = locationabbr, specific_location = locationdesc) %>% 
  filter(topic == "Overall Health") %>% 
  filter(response %in% c("Excellent", "Very good", "Good", "Fair", "Poor")) %>% 
  mutate(response = factor(response), 
         response = forcats::fct_relevel(response, c("Poor", "Fair", "Good", "Very good", "Excellent")))

```

```{r}
BRFSS_df %>% 
  filter(year == 2002) %>% 
  select(state, specific_location) %>% 
  distinct() %>% 
  count(state, name = "ob_n") %>% 
  filter(ob_n >= 7)

BRFSS_df %>% 
  filter(year == 2010) %>% 
  select(state, specific_location) %>% 
  distinct() %>% 
  count(state, name = "ob_n") %>% 
  filter(ob_n >= 7)
```

```{r}
BRFSS_df %>% 
  filter(response == "Excellent") %>% 
  group_by(year, state) %>% 
  mutate(
    mean_value = mean(data_value, na.rm = TRUE)
  ) %>% 
  select(year, state, mean_value) %>% 
  distinct() %>% 
  ggplot(aes(x = year, y = mean_value)) +
  geom_line(aes(group = state, color = state))

```






